device: cuda:0
data: GraphWaveNet_brain_connectivity_v2/data/training_samples_1024
adjdata_nbh: GraphWaveNet_brain_connectivity_v2/data/adj_mx_nbh/norm_spatial_conn_matrix.npy
adjtype: transition
gcn_bool: true
adj_mtx_bool: true
aptonly: false
addaptadj: false
randomadj: true
walk_order: 2
seq_length: 1024
nhid: 32
kernel_size: 4
blocks: 49
layers: 3
in_dim: 1
num_nodes: 64
batch_size: 4
learning_rate: 0.001
learning_rate_step: 10
dropout: 0.3
weight_decay: 0.0001
train_support: GraphWaveNet_brain_connectivity_v2/data/adj_mx_1024/spectral_matrix_train.npy
val_support: GraphWaveNet_brain_connectivity_v2/data/adj_mx_1024/spectral_matrix_val.npy
test_support: GraphWaveNet_brain_connectivity_v2/data/adj_mx_1024/spectral_matrix_test.npy
epochs: 30
print_every: 50
save_dir: null  # Set it to null if you want to indicate no save_dir
expid: 1
save_predictions: true
output_name: outputs