device: cuda:0
checkpoint_dir: results/GWN_4_256_125_1126121127/
checkpoint_model: _exp1_best_0.0357.pth
data: data/training_samples_256_2s_125s_05
adjdata_nbh: data/adj_mx/norm_spatial_conn_matrix.npy
adjtype: symnadj
gcn_bool: true
adj_mtx_bool: false
aptonly: false
addaptadj: false
randomadj: true
walk_order: 2
seq_length: 32
nhid: 32
kernel_size: 4
blocks: 3
layers: 6
in_dim: 1
num_nodes: 64
batch_size: 40
learning_rate: 0.001
learning_rate_step: 10
dropout: 0
weight_decay: 0.0001
train_support: data/adj_mx_1024_2s_375s_05/spectral_matrix_train.npy
val_support: data/adj_mx_1024_2s_375s_05/spectral_matrix_val.npy
test_support: data/adj_mx_1024_2s_375s_05/spectral_matrix_test.npy
epochs: 10
print_every: 50
save_dir: null  # Set it to null if you want to indicate no save_dir
expid: 1
save_predictions: true
output_name: outputs

 
